(() => {
  "use strict";
  let DATA, Fretboard, state, app, helpers, rerender;
  const qualityOptions = ["Maj7", "7", "m7", "m7b5"];
  const tuning = { 1: 64, 2: 59, 3: 55, 4: 50, 5: 45, 6: 40 };
  function configure(context) { ({ DATA, Fretboard, state, app, rerender } = context); helpers = context.helpers; }
  function transpose(form, root) { const offset=DATA.rootOffsets[root]??0; return {...form, frets:form.frets.map(f=>Number(f)+offset)}; }
  function metrics(form, root, shift=0) {
    const v=transpose(form,root), frets=v.frets.map(f=>Number(f)+shift);
    if (frets.some(f=>!Number.isFinite(f)||f<1||f>21)) return null;
    const pitches=frets.map((f,i)=>tuning[v.strings[i]]+f), top=Math.max(...pitches);
    return {...v,frets,topNotePitch:top,topNotePitchClass:((top%12)+12)%12,topNoteFret:frets[pitches.indexOf(top)],topString:v.strings[pitches.indexOf(top)],minFret:Math.min(...frets),maxFret:Math.max(...frets),positionCenter:frets.reduce((a,b)=>a+b,0)/frets.length};
  }
  function candidates(chord, rootOnly=false) {
    return DATA.forms.filter(f=>f.quality===chord.quality&&f.showInBrowseByChord===true&&Number.isInteger(f.browseByChordOrder))
      .filter(f=>rootOnly ? ((f.family==="Drop2"&&f.stringSet==="2-5"||f.family==="Drop3"&&f.stringSet==="2-6")&&f.inversion==="Root") : f.variant!=="Standard")
      .flatMap(f=>[-12,0,12].map(s=>metrics(f,chord.root,s)).filter(Boolean));
  }
  function initial(list, mode) { return [...list].sort((a,b)=>{const ar=a.maxFret<=12?0:1,br=b.maxFret<=12?0:1;if(ar!==br)return ar-br;const center=Math.abs(a.positionCenter-6)-Math.abs(b.positionCenter-6);if(center)return center;if(mode==='asc')return a.topNotePitch-b.topNotePitch;if(mode==='desc')return b.topNotePitch-a.topNotePitch;return a.browseByChordOrder-b.browseByChordOrder;})[0]||null; }
  function choose(prev,list,mode) { if(!prev)return initial(list,mode); return [...list].sort((a,b)=>{const rank=x=>{const d=x.topNotePitch-prev.topNotePitch;if(mode==='asc')return d===0?0:d>0?1:2;if(mode==='desc')return d===0?0:d<0?1:2;return 0};const cmp=rank(a)-rank(b);if(cmp)return cmp;const da=Math.abs(a.topNotePitch-prev.topNotePitch),db=Math.abs(b.topNotePitch-prev.topNotePitch);return da-db||Math.abs(a.positionCenter-prev.positionCenter)-Math.abs(b.positionCenter-prev.positionCenter)||a.positionCenter-b.positionCenter||a.browseByChordOrder-b.browseByChordOrder;})[0]||null; }
  function sequence(mode) { let prev=null; return state.playChords.map(ch=>{const next=mode==='root'?choose(prev,candidates(ch,true),'nearest'):choose(prev,candidates(ch,false),mode);prev=next;return next;}); }
  function card(chord,v) { return `<article class="play-card"${v?` data-play-selected-id="${helpers.escapeHtml(v.id)}" data-play-top="${v.topNotePitch}" data-play-center="${v.positionCenter}"`:''}><h4>${helpers.escapeHtml(chord.root+chord.quality)}</h4>${v?`<p>${helpers.escapeHtml(v.family)} · ${helpers.escapeHtml(v.stringSet)} · ${helpers.escapeHtml(v.inversion)}</p><div class="play-board" data-play-form="${helpers.escapeHtml(v.id)}" data-play-frets="${v.frets.join(',')}"></div>`:'<div class="empty-state compact">No available voicing</div>'}</article>`; }
  function render() { const patterns=[['Ascending','asc'],['Descending','desc'],['Nearest','nearest'],['Root Position','root']]; app.innerHTML=`<div class="play-print-header">Chord Changes – Play<br><span>${helpers.escapeHtml(state.playChords.map(c=>c.root+c.quality).join(' → '))}</span></div><section class="panel play-controls">${state.playChords.map((c,i)=>`<div class="chord-row"><div class="control-group"><label>Root</label><select data-play-index="${i}" data-play-field="root">${helpers.options(DATA.roots,c.root)}</select></div><div class="control-group"><label>Quality</label><select data-play-index="${i}" data-play-field="quality">${helpers.options(qualityOptions,c.quality)}</select></div>${state.playChords.length>2?`<button data-play-remove="${i}" type="button">Remove</button>`:''}</div>`).join('')}<div class="control-group play-view"><span class="control-label">View</span><div class="segmented" data-segment="orientation"><button class="${state.orientation==='horizontal'?'active':''}" data-value="horizontal" type="button">Horizontal</button><button class="${state.orientation==='vertical'?'active':''}" data-value="vertical" type="button">Vertical</button></div></div><button data-play-add type="button"${state.playChords.length>=5?' disabled':''}>Add chord</button><button data-play-refresh type="button">Refresh</button></section>${patterns.map(([name,mode])=>{const s=sequence(mode);return `<section class="pattern-group play-pattern"><div class="pattern-heading"><h3>${name}</h3></div><div class="play-grid">${state.playChords.map((c,i)=>card(c,s[i])).join('')}</div></section>`}).join('')}`; document.querySelectorAll('[data-play-index]').forEach(x=>x.onchange=()=>{state.playChords[+x.dataset.playIndex][x.dataset.playField]=x.value;rerender()});document.querySelector('[data-play-add]')?.addEventListener('click',()=>{if(state.playChords.length<5){state.playChords.push({root:'C',quality:'Maj7'});rerender()}});document.querySelectorAll('[data-play-remove]').forEach(x=>x.onclick=()=>{state.playChords.splice(+x.dataset.playRemove,1);rerender()});document.querySelector('[data-play-refresh]')?.addEventListener('click',rerender);document.querySelectorAll("[data-segment='orientation'] button").forEach(x=>x.onclick=()=>{state.orientation=x.dataset.value;rerender()});document.querySelectorAll('[data-play-form]').forEach((host,i)=>{const v=sequence(patterns[Math.floor(i/state.playChords.length)][1])[i%state.playChords.length];if(v)Fretboard.render(host,{...v,frets:v.frets},{size:'small',orientation:state.orientation,showDegrees:state.showDegrees,preserveAbsolutePositions:true})}); }
  window.GVL_PLAY={configure,render};
})();
